spring.datasource.url: jdbc:${JAWSDB_URL:mysql://localhost:3306/blog?useJvmCharsetConverters=true}
spring.datasource.username: vlad
spring.datasource.password: testtest
spring.jpa.hibernate.dll-auto: none
spring.jpa.show-sql: true
server.port: ${PORT:8080}
changeLogFile: /src/main/resources/db/changelog/db.changelog-master.yaml
referenceUrl: hibernate:spring:ru.usharik.liquibase.demo.persist.model?dialect=org.hibernate.dialect.MySQLDialect
diffChangeLogFile: /src/main/resources/db/changelog/db.changelog-@timestamp@.yaml
ignoreClasspathPrefix: true

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: vladStatsenko1@gmail.com
spring.mail.password: rfhfcbrbQ1
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 915 861-73-63
blog.email: vladStatsenko1@gmail.com
blog.copyright: Стаценко Владислав
blog.copyrightFrom: 2021

blog.maxFileSize: 5242880